#!/bin/bash
#HEAD#########################################################
#
# Katana Framework | dependencies
# The below dependencies this installed in most pentest distros,
# but in other distro's as UBUNTU not is installed.
#
# aircrack-ng for wireless modules
# nmap for network scan modules and some functions
# apache2 for SET modules
# ettercap for MIMT modules
# dhcpd for rogues AP
#
# 
# Last Modified: 03/06/2016
#
#########################################################HEAD#

#sudo apt-get update
#sudo apt-get upgrade

	if ! hash aircrack-ng 2>/dev/null; then 
		sudo apt-get install --yes aircrack-ng
	fi

	if ! hash nmap 2>/dev/null; then 
		sudo apt-get install --yes nmap
	fi

	if ! hash apache2 2>/dev/null; then 
		sudo apt-get install --yes apache2 php5 libapache2-mod-php5
	fi

	if ! hash ettercap 2>/dev/null; then 
		sudo apt-get install ettercap-text-only
	fi

	if ! hash dhcpd 2>/dev/null; then 
		sudo apt-get install isc-dhcp-server
	fi

	if ! hash hostapd 2>/dev/null; then 
		sudo apt-get install hostapd
	fi
	
DIR=$(dirname $0)
cd $DIR/lib/scapy/
sudo python setup.py install
