/*!CK:2256121960!*//*1417407519,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["uU7Pt"]); }

__d("AdsOtherConsts",[],function(a,b,c,d,e,f){e.exports={REACH_TOO_LOW_NUMBER:1000};},null);
__d("List.react",["ReactPropTypes","React","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){var k=h.createClass({displayName:"List",propTypes:{border:g.oneOf(['none','light','medium','dark']),spacing:g.oneOf(['none','small','medium','large']),direction:g.oneOf(['vertical','horizontal']),valign:g.oneOf(['baseline','top','middle','bottom']),edgepadding:g.bool},getDefaultProps:function(){return {border:'medium',spacing:'medium',direction:'vertical',valign:'top'};},render:function(){var l=this.props.border,m=this.props.direction,n=this.props.spacing,o=m==='horizontal'&&this.props.valign,p,q,r;p=((m==='vertical'?"_4kg":'')+(m==='horizontal'?' '+"_4ki":'')+(o==='top'?' '+"_509-":'')+(o==='middle'?' '+"_509_":'')+(o==='bottom'?' '+"_50a0":''));if(n!=='none'||l!=='none')q=((l==='none'?"_6-i":'')+(l==='light'?' '+"_4ks":'')+(l==='medium'?' '+"_4kt":'')+(l==='dark'?' '+"_4ku":''));if(n!=='none')r=((!this.props.edgepadding?"_6-h":'')+(n==='small'?' '+"_704":'')+(n==='medium'?' '+"_6-j":'')+(n==='large'?' '+"_703":''));var s=j("uiList",p,q,r);return (h.createElement("ul",h.__spread({},this.props,{className:j(this.props.className,s)}),this.props.children));}});e.exports=k;},null);
__d("XUIBlock",["ReactPropTypes","cx"],function(a,b,c,d,e,f,g,h){var i={propTypes:{background:g.oneOf(['base-wash','light-wash','white','highlight','transparent'])},getDefaultProps:function(){return {background:'transparent'};},getBackgroundClass:function(j){var k=((j.background==='base-wash'?"_4-u5":'')+(j.background==='light-wash'?' '+"_57d8":'')+(j.background==='white'?' '+"_4-u8":'')+(j.background==='highlight'?' '+"_4-u7":''));return k;}};e.exports=i;},null);
__d("XUICard.react",["React","XUIBlock","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){var k=g.createClass({displayName:"XUICard",propTypes:h.propTypes,getDefaultProps:h.getDefaultProps,render:function(){var l=j("_4-u2",h.getBackgroundClass(this.props));return (g.createElement("div",g.__spread({},this.props,{className:j(this.props.className,l)}),this.props.children));}});e.exports=k;},null);
__d("XUICardSection.react",["React","XUIBlock","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){var k=g.createClass({displayName:"XUICardSection",propTypes:h.propTypes,getDefaultProps:h.getDefaultProps,render:function(){var l=j("_4-u3",h.getBackgroundClass(this.props));return (g.createElement("div",g.__spread({},this.props,{className:j(this.props.className,l)}),this.props.children));}});e.exports=k;},null);
__d("XUIDialogCancelButton.react",["React","XUIDialogButton.react","fbt"],function(a,b,c,d,e,f,g,h,i){var j=g.createClass({displayName:"XUIDialogCancelButton",render:function(){return (g.createElement(h,g.__spread({},this.props,{action:"cancel",label:"Cancel"})));}});e.exports=j;},null);
__d("sliceChildren",["flattenChildren"],function(a,b,c,d,e,f,g){"use strict";function h(i,j,k){if(i==null)return i;var l={},m=g(i),n=0;for(var o in m){if(!m.hasOwnProperty(o))continue;var p=m[o];if(n>=j)l[o]=p;n++;if(k!=null&&n>=k)break;}return l;}e.exports=h;},null);
__d("XUIDialogTitle.react",["LeftRight.react","React","ReactPropTypes","XUICloseButton.react","cx","fbt","sliceChildren","joinClasses"],function(a,b,c,d,e,f,g,h,i,j,k,l,m,n){var o=h.createClass({displayName:"XUIDialogTitle",propTypes:{closeButtonText:i.string,showCloseButton:i.bool},getDefaultProps:function(){return {closeButtonText:"Close",showCloseButton:true};},render:function(){var p=null;if(this.props.showCloseButton)p=h.createElement(j,{label:this.props.closeButtonText,className:"layerCancel _51-t"});return (h.createElement("div",h.__spread({},this.props,{className:n(this.props.className,"_4-i0")}),h.createElement(g,null,h.createElement("h3",{className:"_52c9"},m(this.props.children,0,1)),h.createElement("div",{className:"_51-u"},m(this.props.children,1),p))));}});e.exports=o;},null);
__d("XUINotice.react",["React","Image.react","XUICloseButton.react","cx","fbt","ix","joinClasses"],function(a,b,c,d,e,f,g,h,i,j,k,l,m){'use strict';var n=g.PropTypes,o={notify:{altText:"Notice",className:null,iconSrc:l('/images/ui/x/glyphs/flat/info-flat_m.png')},success:{altText:"Success",className:"_3qh4",iconSrc:l('/images/ui/x/glyphs/flat/checkmark_white_m.png')},warn:{altText:"Warning",className:"_585o",iconSrc:l('/images/ui/x/glyphs/flat/error-flat_m.png')}},p=g.createClass({displayName:"XUINotice",propTypes:{onDismiss:n.func,use:n.oneOf(Object.keys(o))},getDefaultProps:function(){return {use:'notify'};},render:function(){var q=this.props,r=q.children,s=q.className,t=q.onDismiss,u=q.use,v=(function(y,z){var aa={},ba=Object.prototype.hasOwnProperty;if(y==null)throw new TypeError();for(var ca in y)if(ba.call(y,ca)&&!ba.call(z,ca))aa[ca]=y[ca];return aa;})(q,{children:1,className:1,onDismiss:1,use:1}),w=o[u];s=m("_585n",w.className,s);var x=null;if(t)x=g.createElement(i,{className:"_585q",href:"#",onClick:t});return (g.createElement("div",g.__spread({},v,{className:s}),g.createElement(h,{alt:w.altText,className:"_585p",src:w.iconSrc}),x,g.createElement("div",{className:"_585r _50f4"},r)));}});e.exports=p;},null);
__d("TypeaheadViewPropTypes",["React"],function(a,b,c,d,e,f,g){var h=g.PropTypes,i={ariaOwneeID:h.string,highlightedEntry:h.object,entries:h.array.isRequired,onSelect:h.func.isRequired,onHighlight:h.func,onRenderHighlight:h.func,role:h.string};e.exports=i;},null);
__d("XUITypeaheadViewItem.react",["React","TypeaheadViewItem","BackgroundImage.react","Badge.react","ImageBlock.react","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j,k,l,m){var n=g.createClass({displayName:"XUITypeaheadViewItem",mixins:[h.Mixin],propTypes:h.propTypes,render:function(){var o=this.props.entry,p=o.getSubtitle().split(' \u00b7 ')[0],q=p?g.createElement("div",{className:"_599q"},p):null,r=o.getPhoto()?g.createElement(i,{width:32,height:32,backgroundSize:"cover",src:o.getPhoto()}):g.createElement("span",null),s=o.getAuxiliaryData(),t=null;if(s&&s.verified)t=g.createElement(j,null);var u=(("_599m")+(!q?' '+"_5mne":'')+(this.props.highlighted?' '+"_599n":''));u=m(u,this.props.className);return (g.createElement("li",{"aria-label":o.getTitle(),"aria-selected":this.props.highlighted,className:u,onMouseDown:this._onSelect,onMouseEnter:this._onHighlight,role:this.props.role,title:o.getTitle()},g.createElement(k,{spacing:"medium"},r,g.createElement("div",null,g.createElement("div",{className:"_599p"},o.getTitle(),t),q))));}});e.exports=n;},null);
__d("XUITypeaheadView.react",["React","TypeaheadViewPropTypes","XUITypeaheadViewItem.react","cx"],function(a,b,c,d,e,f,g,h,i,j){var k=g.createClass({displayName:"XUITypeaheadView",propTypes:h,getDefaultProps:function(){return {role:'listbox'};},_renderItem:function(l){var m=l===this.props.highlightedEntry;return (g.createElement(i,{key:l.getUniqueID(),entry:l,highlighted:m,onSelect:this.props.onSelect,onHighlight:this.props.onHighlight,onRenderHighlight:this.props.onRenderHighlight}));},render:function(){var l=(("_599r")+(!this.props.entries.length?' '+"_599s":''));return (g.createElement("ul",{className:l,id:this.props.ariaOwneeID,role:this.props.role},this.props.entries.map(this._renderItem)));}});e.exports=k;},null);
__d("ManagedError",[],function(a,b,c,d,e,f){function g(h,i){Error.prototype.constructor.call(this,h);this.message=h;this.innerError=i;}g.prototype=new Error();g.prototype.constructor=g;e.exports=g;},null);
__d("GiftCredits",["AsyncRequest","Dialog","URI"],function(a,b,c,d,e,f,g,h,i){var j={dialog:null,callback:null,purchaseLock:false,purchaseLockExpiryThreshold:5000,purchaseLockTimeoutId:null,getPurchaseCreditPrompt:function(k,l,m,n){j.main(k,null,null,null,m,null,null,null,'BuyCredits',{},n);},redeemGiftcard:function(k,l,m){var n=i(document.location).setPath('/giftcards').toString();j.main(k,null,null,n,null,null,null,null,l,{},m);},getPrompt:function(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha){j.main(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha);},main:function(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha){if(j.isPurchaseLocked())return false;j.setPurchaseLock(true);var ia={_path:'pay',method:'pay',display:'async',app_id:k,receiver:l,api_key:q,credits_purchase:x,action:s,next:n,dev_purchase_params:JSON.stringify(t),additional_params:JSON.stringify(u),order_info:JSON.stringify(m),product:v,package_id:w,request_id:y,sdk:z,quantity:aa,quantity_min:ba,quantity_max:ca,test_currency:da,pricepoint_id:ea,user:fa,user_hash:ga,ingame_gift_data:ha},ja=new g().setURI('/fbml/ajax/dialog/').setData(ia).setMethod('GET').setReadOnly(true).setStatusElement('commerce_get_more_loading');j.callback=o;j.dialog=new h().setAsync(ja).setModal(true).setCloseHandler(function(ka){j.setPurchaseLock(false);o(ka);}).show();},isPurchaseLocked:function(){return j.purchaseLock;},setPurchaseLock:function(k){j.purchaseLock=k;if(k){j.purchaseLockTimeoutId=setTimeout(function(){j.setPurchaseLock(false);},j.purchaseLockExpiryThreshold);}else clearTimeout(j.purchaseLockTimeoutId);return true;}};e.exports=j;},null);
__d("legacy:giftcredits",["GiftCredits"],function(a,b,c,d){a.GiftCredits=b('GiftCredits');},3);
__d("AssertionError",["ManagedError"],function(a,b,c,d,e,f,g){function h(i){g.prototype.constructor.apply(this,arguments);}h.prototype=new g();h.prototype.constructor=h;e.exports=h;},null);
__d("Assert",["AssertionError","sprintf"],function(a,b,c,d,e,f,g,h){function i(n,o){if(typeof n!=='boolean'||!n)throw new g(o);return n;}function j(n,o,p){var q;if(o===(void 0)){q='undefined';}else if(o===null){q='null';}else{var r=Object.prototype.toString.call(o);q=/\s(\w*)/.exec(r)[1].toLowerCase();}i(n.indexOf(q)!==-1,p||h('Expression is of type %s, not %s',q,n));return o;}function k(n,o,p){i(o instanceof n,p||'Expression not instance of type');return o;}function l(n,o){m['is'+n]=o;m['maybe'+n]=function(p,q){if(p!=null)o(p,q);};}var m={isInstanceOf:k,isTrue:i,isTruthy:function(n,o){return i(!!n,o);},type:j,define:function(n,o){n=n.substring(0,1).toUpperCase()+n.substring(1).toLowerCase();l(n,function(p,q){i(o(p),q);});}};['Array','Boolean','Date','Function','Null','Number','Object','Regexp','String','Undefined'].forEach(function(n){l(n,j.bind(null,n.toLowerCase()));});e.exports=m;},null);