#
# Katana framework 
# @Katana Setting
#

# DEFAULT FILES NAME
KTFCONSOLE="ktf.console"
KTFLINKER="ktf.linker"
KTFRUN="ktf.run"
KTFLAB="ktf.lab"
KTFGUI="ktf.gui"

# DEFAULT SETTING NETWORK
LOCAL_IP="127.0.0.1"
INTERFACE_DEVICE="wlan1"
INTERFACE_MONITOR="mon0"
MAC_TARGET="AA:A1:BB:B2:CC:C1"
CHANNEL_TARGET="9"
ESSID_TARGET="FUCK-ME"
MY_IP="192.168.1.225"
GATEWAY_ADR="192.168.1.254"

# DEFAUTL PATCHS
PATCH_WWW="/var/www/html/"
PATCH_INTALL="/usr/share/"

# DEFAULT DATE
EMAIL="root@localhost"
USERNAME="root"
PASSWORD="toor"
TABLE_FOLDER_ADMIN="core/db/commons-dir-admin.tbl"
DITIONARY_PASSWORDS="core/db/pass.dicc"
DEFAUTL_LONGITED="5"

# DEFAULT PORT
FTP_PORT="21"
HTTP_PORT="80"
POP_PORT="110"
SQL_PORT="3306"
SSH_PORT="22"
SMTP_PORT="25"

# PATHS SCRIPTS 
NMAP_PATH="/usr/bin/nmap"


