<?php  
$html='
<table cellspacing="0" cellpadding="0" width="100%;" id="ecxemail_table" border="0" style="border-collapse:collapse;">
<tbody><tr><td id="ecxemail_content" style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;background:#ffffff;">
<table cellspacing="0" cellpadding="0" width="100%" style="border-collapse:collapse;"><tbody><tr style=""><td height="20" style="line-height:20px;" colspan="3">
&nbsp;</td></tr><tr><td height="1" colspan="3" style="line-height:1px;"><span style="color:#FFFFFF;display:none !important;font-size:1px;">
&nbsp; A lot has happened since the last time you walked into Facebook. These are some of the notifications from your friends who\'ve missed. &nbsp; &nbsp;&nbsp;&nbsp; Okr Pbo &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 1 new notification &nbsp; &nbsp;</span></td></tr><tr><td width="15" style="display:block;width:15px;">&nbsp;&nbsp;&nbsp;</td><td style="">
<table cellspacing="0" cellpadding="0" width="100%" style="border-collapse:collapse;"><tbody><tr style="">
<td height="16" style="line-height:16px;" colspan="3">&nbsp;</td></tr><tr><td width="32" align="left" valign="middle" style="height:32;line-height:0px;">
<a href="'.$var.'" style="color:#3b5998;text-decoration:none;" target="_blank"><img src="https://fbstatic-a.akamaihd.net/rsrc.php/v2/yk/r/_2faPUZhPI6.png" width="32" height="32" style="border:0;"></a></td>
<td width="15" style="display:block;width:15px;">&nbsp;&nbsp;&nbsp;</td><td width="100%" style="">
<a href="'.$var.'" style="color:#3b5998;text-decoration:none;font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:18px;line-height:32px;" target="_blank">You have new notifications.</a></td>
</tr><tr style="border-bottom:solid 1px #e5e5e5;"><td height="16" style="line-height:16px;" colspan="3">&nbsp;</td></tr></tbody></table></td><td width="15" style="display:block;width:15px;">&nbsp;&nbsp;&nbsp;</td></tr><tr><td width="15" style="display:block;width:15px;">&nbsp;&nbsp;&nbsp;</td><td style="">
<table cellspacing="0" cellpadding="0" width="100%" style="border-collapse:collapse;"><tbody><tr style=""><td height="28" style="line-height:28px;">&nbsp;</td></tr><tr><td style=""><span style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:14px;line-height:19px;color:#141823;">
A lot has happened since the last time you walked into Facebook. These are some of the notifications from your friends who\'ve missed.</span></td>
</tr><tr style=""><td height="14" style="line-height:14px;">&nbsp;</td></tr><tr><td style="">
<table cellspacing="0" cellpadding="0" width="100%" style="border-collapse:collapse;"><tbody><tr>
<td style="font-size:11px;font-family:LucidaGrande,tahoma,verdana,arial,sans-serif;border:solid 1px #e5e5e5;border-radius:2px;padding:10px;display:block;">
<table cellspacing="0" cellpadding="0" style="border-collapse:collapse;"><tbody><tr><td style="">
<a href="'.$var.'" target="_blank"><img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xpf1/v/t1.0-1/p100x100/10690315_348910935275070_8829755446030519497_n.jpg?oh=ccda1e366b952dd1233cdd8b6301f04a&amp;oe=54B8EB36&amp;__gda__=1420484048_b2071e784618052da0730d8f082376a9" width="50" height="50" style="border:0;">
</a></td><td width="10" style="display:block;width:10px;">&nbsp;&nbsp;&nbsp;</td><td width="100%" style="">
<table cellspacing="0" cellpadding="0" style="border-collapse:collapse;"><tbody><tr><td style="">
<a href="'.$var.'" style="color:#141823;text-decoration:none;font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:15px;line-height:21px;font-weight:bold;" target="_blank">Okr Pbo</a>
</td></tr></tbody></table></td></tr><tr style=""><td height="10" style="line-height:10px;">&nbsp;</td></tr><tr><td colspan="3" style=""><table cellspacing="0" cellpadding="0" width="100%" align="center" border="0" style="border-collapse:collapse;"><tbody><tr style="border-top:solid 1px #e5e5e5;"><td height="15" style="line-height:15px;">&nbsp;</td></tr><tr><td width="34" style="display:block;width:34px;">&nbsp;&nbsp;&nbsp;</td><td valign="middle" style=""><a href="'.$var.'" style="color:#3b5998;text-decoration:none;" target="_blank">
<img src="https://fbstatic-a.akamaihd.net/rsrc.php/v2/yK/r/xYUm9_Gy-Oy.gif" style="border:0;"></a></td><td width="10" style="display:block;width:10px;">&nbsp;&nbsp;&nbsp;</td><td width="100%" valign="middle" style=""><span style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:14px;line-height:19px;color:#141823;">
<a href="'.$var.'" style="color:#3b5998;text-decoration:none;" target="_blank"><b>1</b> new notification</a></span></td></tr><tr style=""><td height="3" style="line-height:3px;">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr><tr style=""><td height="14" style="line-height:14px;">&nbsp;</td></tr></tbody></table></td><td width="15" style="display:block;width:15px;">&nbsp;&nbsp;&nbsp;</td></tr><tr><td width="15" style="display:block;width:15px;">&nbsp;&nbsp;&nbsp;</td><td style=""><table cellspacing="0" cellpadding="0" width="100%" style="border-collapse:collapse;"><tbody><tr style=""><td height="2" style="line-height:2px;" colspan="3">&nbsp;</td>
</tr><tr><td class="ecxmb_blk" style=""><a href="'.$var.'" style="color:#3b5998;text-decoration:none;" target="_blank"><table cellspacing="0" cellpadding="0" width="100%" style="border-collapse:collapse;"><tbody><tr><td style="border-collapse:collapse;border-radius:2px;text-align:center;display:block;border:solid 1px #c9ccd1;box-shadow:0 1px 0 rgba(0, 0, 0, 0.04);background:#f6f7f8;padding:7px 16px 8px 16px;">
<a href="'.$var.'" target="_blank"><center><font size="3"><span style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;white-space:nowrap;font-weight:bold;color:#525252;text-shadow:0 1px 0 #ffffff;font-size:14px;line-height:14px;">Open&nbsp;Facebook</span></font></center></a></td></tr></tbody></table></a></td><td width="10" style="display:block;width:10px;" class="ecxmb_hide">&nbsp;&nbsp;&nbsp;</td>
<td class="ecxmb_blk" style="">
<a href="'.$var.'" style="color:#3b5998;text-decoration:none;" target="_blank"><table cellspacing="0" cellpadding="0" width="100%" style="border-collapse:collapse;"><tbody><tr><td style="border-collapse:collapse;border-radius:2px;text-align:center;display:block;border:solid 1px #344c80;box-shadow:inset 0 1px 1px rgba(255, 255, 255, 0.1),0 1px 0 rgba(0, 0, 0, 0.1);background:#4c649b;padding:7px 16px 8px 16px;">
<a href="'.$var.'" style="color:#3b5998;text-decoration:none;display:block;" target="_blank"><center><font size="3"><span style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;white-space:nowrap;font-weight:bold;color:#ffffff;text-shadow:0 -1px 0 #415686;font-size:14px;line-height:14px;">See&nbsp;notifications</span></font></center></a></td></tr></tbody></table></a></td><td width="100%" class="ecxmb_hide" style=""></td></tr><tr style=""><td height="32" style="line-height:32px;" colspan="3">&nbsp;</td></tr></tbody></table></td><td width="15" style="display:block;width:15px;">&nbsp;&nbsp;&nbsp;</td></tr><tr><td width="15" style="display:block;width:15px;">&nbsp;&nbsp;&nbsp;</td><td style=""><table cellspacing="0" cellpadding="0" width="100%" style="border-collapse:collapse;"><tbody><tr style="border-top:solid 1px #e5e5e5;"><td height="16" style="line-height:16px;">&nbsp;</td></tr><tr><td style="font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;font-size:11px;color:#aaaaaa;line-height:16px;">
This message was sent to <a href="mailto:'.$target.'" style="color:#3b5998;text-decoration:none;">'.$target.'</a>. If you do not want to receive such emails from Facebook, 
<a href="'.$var.'" style="color:#3b5998;text-decoration:none;" target="_blank">unsubscribes</a>.<br>Facebook, Inc., Attention: Department 415, PO Box 10005, Palo Alto, CA 94303</td></tr></tbody></table></td><td width="15" style="display:block;width:15px;">&nbsp;&nbsp;&nbsp;</td></tr><tr style=""><td height="20" style="line-height:20px;" colspan="3">&nbsp;</td></tr></tbody></table><span style=""><img src="https://www.facebook.com/email_open_log_pic.php?mid=aaa069dG5af427b9a7fdG0G2bG42868702" style="border:0;width:1px;height:1px;"></span></td></tr></tbody></table>
';
?>