Archive: files/rar3-comment-plain.rar
  comment='RARcomment\n'
FILE: hdrlen=43 datlen=8 hdr_unknown=0
  flags=0x9020:EXTTIME,LONG,D128
  os=3:UNIX ver=29 mode=0100644 meth=3 cmp=8 dec=0 vol=0
  crc=0x00000000 (0) time=2010-11-02 10:03:25
  name=file1.txt
  mtime=2010-11-02 10:03:25
  comment='Comment1v2\n'
FILE: hdrlen=43 datlen=8 hdr_unknown=0
  flags=0x9020:EXTTIME,LONG,D128
  os=3:UNIX ver=29 mode=0100644 meth=3 cmp=8 dec=0 vol=0
  crc=0x00000000 (0) time=2010-11-02 10:03:25
  name=file2.txt
  mtime=2010-11-02 10:03:25
  comment='Comment2v2\n'
